(let ((emacs_loadfile (expand-file-name "emacs" user-emacs-directory)))
  (let ((emacs_org (concat emacs_loadfile ".org"))
	(emacs_elc (concat emacs_loadfile ".elc")))
    (if (file-newer-than-file-p emacs_org emacs_elc)
      (progn
	(setq load-prefer-newer t)
	(let ((default-directory (expand-file-name "lisp" user-emacs-directory)))
	  (normal-top-level-add-subdirs-to-load-path))
	(org-babel-load-file emacs_org t))
      (load emacs_loadfile))))
