execute "augroup Personal"
autocmd!

" core
set clipboard=unnamed,unnamedplus
set confirm
set hidden
set ignorecase smartcase
set lazyredraw
set mouse=ar
set nrformats=alpha,octal,hex,bin
set omnifunc=syntaxcomplete#Complete
set splitbelow splitright
set timeoutlen=500
set updatetime=500

let g:mapleader="\<space>"

noremap <silent> s        <nop>
noremap <silent> S        <nop>
noremap <silent> <leader> <nop>

noremap <silent> Y y$
noremap <silent> Q @@

nnoremap <silent> <leader>l :lopen<cr>
nnoremap <silent> <leader>q :copen<cr>

autocmd FileType help,qf nnoremap <silent> <buffer> <esc> :q<cr>

silent! execute "mkspell! " . fnamemodify($MYVIMRC, ":h") . "/spell/*.add"
autocmd VimEnter * silent! helptags ALL

" aesthetics
set cursorline cursorcolumn colorcolumn=80
set nowrap linebreak
set number relativenumber
set tabstop=4 shiftwidth=4 expandtab
set termguicolors

colorscheme gruvbox

let g:asmsyntax='nasm'

" vim/neovim compat
if has("nvim")
    set inccommand=split
    set shada=
else
    let &t_EI = "\<esc>[1 q"
    let &t_SI = "\<esc>[5 q"
    let &t_SR = "\<esc>[3 q"

    let &t_8f = "\<esc>[38:2:%lu:%lu:%lum"
    let &t_8b = "\<esc>[48:2:%lu:%lu:%lum"
    set background=dark
    set hlsearch incsearch

    set autoindent
    set backspace=indent,eol,start

    set viminfo=

    syntax enable
endif

" vim-dirvish
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>

" vim-fugitive
autocmd FileType fugitive nnoremap <silent> <buffer> <esc> :q<cr>
nnoremap <silent> <leader>g :Git<cr>

" fzf
let $FZF_DEFAULT_COMMAND="fd --hidden --type=file"
nnoremap <silent> <leader>f :FZF<cr>

" vim-highlightedyank
let g:highlightedyank_highlight_duration = 500

execute "augroup END"
