execute "augroup Personal"
autocmd!

" vim/neovim compat
if has("nvim")
    set inccommand=nosplit
    set shada=
    
    autocmd TextYankPost * lua vim.highlight.on_yank{timeout=500}
else
    if &term =~ "-256color$"
        set term=xterm-256color
        " set key codes AFTER term
        let &t_SI = "\<esc>[6 q"
        let &t_SR = "\<esc>[4 q"
        let &t_EI = "\<esc>[2 q"
    endif
    inoremap <esc> <esc>jk

    set background=dark
    set hlsearch incsearch

    set autoindent
    set backspace=indent,eol,start,nostop

    set viminfo=

    set directory=~/.local/share/vim/swap//
    filetype plugin indent on
    syntax enable

    " vim-highlightedyank
    let g:highlightedyank_highlight_duration = 500
    packadd vim-highlightedyank

endif

" core
set clipboard=unnamed,unnamedplus
set confirm
set hidden
set ignorecase smartcase
set lazyredraw
set mouse=ar
set nrformats=alpha,octal,hex,bin
set omnifunc=syntaxcomplete#Complete
set splitbelow splitright
set timeoutlen=500
set updatetime=500

let g:mapleader="\<space>"

noremap <silent> s        <nop>
noremap <silent> S        <nop>
noremap <silent> <leader> <nop>

noremap <silent> Y y$
noremap <silent> Q @@

nnoremap <silent> <leader>l :lopen<cr>
nnoremap <silent> <leader>q :copen<cr>

autocmd FileType qf nnoremap <silent> <buffer> <esc> :q<cr>

silent! execute "mkspell! " . fnamemodify($MYVIMRC, ":h") . "/spell/*.add"
autocmd VimEnter * silent! helptags ALL

" aesthetics
set cursorline cursorcolumn colorcolumn=80
set guioptions=f
set laststatus=0 showtabline=0
set noruler
set nowrap linebreak
set number relativenumber
set shortmess=o
set tabstop=4 shiftwidth=4 expandtab
set termguicolors

colorscheme gruvbox

let g:asmsyntax='nasm'

" vim-dirvish
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish <args>
command! -nargs=? -complete=dir Vexplore leftabove vsplit | silent Dirvish <args>

" vim-fugitive
autocmd FileType fugitive nnoremap <silent> <buffer> <esc> :q<cr>
nnoremap <silent> <leader>g :Git<cr>

" fzf
nnoremap <silent> <leader>f :call fzf#run({"window": {"width": 0.8, "height": 0.6}, "source": "fd -Htf", "sink": "e"})<cr>
nnoremap <silent> <leader>c :call fzf#run({"window": {"width": 0.8, "height": 0.6}, "source": "fd -Htd & ancestors", "sink": "cd"})<cr>
autocmd FileType fzf tnoremap <silent> <esc> <c-c>

" vim-sandwich
let g:sandwich#recipes = [
            \ {'buns': ['(', ')'], 'nesting': 1, 'input': ['(', ')', 'b']},
            \ {'buns': ['{', '}'], 'nesting': 1, 'skip_break': 1, 'input': ['{', '}', 'B']},
            \ {'buns': ['[', ']'], 'nesting': 1, 'input': ['[', ']', 'r']},
            \ {'buns': ['<', '>'], 'expand_range': 0},
            \ {'buns': ['"', '"'], 'quoteescape': 1, 'expand_range': 0, 'nesting': 0, 'linewise': 0},
            \ {'buns': ["'", "'"], 'quoteescape': 1, 'expand_range': 0, 'nesting': 0, 'linewise': 0},
            \ {'buns': ["`", "`"], 'quoteescape': 1, 'expand_range': 0, 'nesting': 0, 'linewise': 0},
            \ ]

execute "augroup END"
